name: Jekyll CI - Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * *"

jobs:
  page-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod a+w /srv/jekyll/Gemfile.lock && chmod 777 /srv/jekyll && jekyll build --future"
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SiteForTest
        path: _site

  HTMLProofer:

    runs-on: ubuntu-latest

    needs: page-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: SiteForTest

      - name: HTMLProofer
        uses: chabad360/htmlproofer@v1.1
        with:
            directory: "./SiteForTest"
